name: Run Tonomy-ID tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.4.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.4.1
      - run: npm install
      - run: npm test
