name: Tonomy ID Bump Version Number

on:
  pull_request:
    types:
      - closed

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    env:
      NODE_ENV: staging

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: "v"
